### official language mapping
##  country code:  language codes

af: fa,ps
bd: bn
bn: ms
cn: zh
hk: zh,en
id: id
in: hi,en
jp: ja
kg: ky,ru
kh: km
kp: ko
kr: ko,en
kz: kk,ru
la: lo
lk: si,ta
lr: en
mm: my
mn: mn
mv: dv
my: ms
np: ne
ph: en,tl
pk: en,ur
sg: en,ms,zh,ta
th: th
tj: tg,ru
tl: pt # tet
tm: tk
tw: zh
uz: uz # kaa
vn: vi

